# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    outputs:
      enable: ${{ steps.ok-to-test.outputs.enable }}
    steps:
      - name: Check if run ci
        id: check-ci-enable
        uses: actions/github-script@v3
        with:
          script: |
            console.log(process.env.GITHUB_HEAD_REF + "," + process.env.GITHUB_BASE_REF)
            const isDefaultBranch = process.env.GITHUB_HEAD_REF === process.env.GITHUB_BASE_REF
            console.log(isDefaultBranch);
            console.log(process.env.GITHUB_HEAD_REF === 'master');
            console.log(process.env.GITHUB_HEAD_REF == 'master' );
            if (isDefaultBranch) {
              return 'true'
            }

            const okToTest = context.payload.pull_request.labels
                 .map(label => label.name)
                 .includes("ok-to-test")

            if (!okToTest) {
              core.setFailed("Please add ok-to-test label.");
            }
            return okToTest
          result-encoding: string
      - name: Set output
        id: ok-to-test
        run: echo "::set-output name=enable::${{ steps.check-ci-enable.outputs.result }}"
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
